### ISSUE TITLE
Allow slider control to use a configurable step value  

### ISSUE THREAD

**Issue by guyaparker** [CenturyLinkCloud/Cyclops#30]
Allowing the slider control to use a step value other than 1 would make it more useful for configuring things like disk size where something like 50GB increments would be more appropriate.

**Comment by osbornm** [comment]
General questions on behavior to discuss prior to implementing: 

- Does the range need to be wholly divisible by the step? 
- What happens if the current value is not on a step boundary? e.g. an "custom" disk with 32GB of storage is shown but the step is 5GB? Very likely for OS disks on our templates
- While the step jumps the slider is it still valid to allow a number between steps. step is 5 but I want 7

**Comment by guyaparker** [comment]
The default HTML5 input behavior with a step attribute is...
- the range does not need to be divisible by the step.
- a current value that is not a step is shown and is valid but once changed cannot be selected again using the arrows in the input field.
- typing a value that is not a step is possible.

So the slider is simply a graphical alternative to the HTML5 step selection mechanism. If additional restrictions are required then either a select list or additional validation is required.

**Comment by osbornm** [comment]
won't fix, hasn't been an issue.
